/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ParcelsRouteImport } from './routes/parcels'
import { Route as ProviderDashboardRouteImport } from './routes/provider-dashboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as StayRouteImport } from './routes/stay'
import { Route as TiffinRouteImport } from './routes/tiffin'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ProviderProviderIdRouteImport } from './routes/provider.$providerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsRoute = ParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/provider-dashboard',
  path: '/provider-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinRoute = TiffinRouteImport.update({
  id: '/tiffin',
  path: '/tiffin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderProviderIdRoute = ProviderProviderIdRouteImport.update({
  id: '/provider/$providerId',
  path: '/provider/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/parcels': typeof ParcelsRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/stay': typeof StayRoute
  '/tiffin': typeof TiffinRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/parcels': typeof ParcelsRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/stay': typeof StayRoute
  '/tiffin': typeof TiffinRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/parcels': typeof ParcelsRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/stay': typeof StayRoute
  '/tiffin': typeof TiffinRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/logistics'
    | '/orders'
    | '/parcels'
    | '/provider-dashboard'
    | '/register'
    | '/roadmap'
    | '/stay'
    | '/tiffin'
    | '/order/$orderId'
    | '/provider/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/logistics'
    | '/orders'
    | '/parcels'
    | '/provider-dashboard'
    | '/register'
    | '/roadmap'
    | '/stay'
    | '/tiffin'
    | '/order/$orderId'
    | '/provider/$providerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/logistics'
    | '/orders'
    | '/parcels'
    | '/provider-dashboard'
    | '/register'
    | '/roadmap'
    | '/stay'
    | '/tiffin'
    | '/order/$orderId'
    | '/provider/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LogisticsRoute: typeof LogisticsRoute
  OrdersRoute: typeof OrdersRoute
  ParcelsRoute: typeof ParcelsRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  RegisterRoute: typeof RegisterRoute
  RoadmapRoute: typeof RoadmapRoute
  StayRoute: typeof StayRoute
  TiffinRoute: typeof TiffinRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ProviderProviderIdRoute: typeof ProviderProviderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels': {
      id: '/parcels'
      path: '/parcels'
      fullPath: '/parcels'
      preLoaderRoute: typeof ParcelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-dashboard': {
      id: '/provider-dashboard'
      path: '/provider-dashboard'
      fullPath: '/provider-dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin': {
      id: '/tiffin'
      path: '/tiffin'
      fullPath: '/tiffin'
      preLoaderRoute: typeof TiffinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$providerId': {
      id: '/provider/$providerId'
      path: '/provider/$providerId'
      fullPath: '/provider/$providerId'
      preLoaderRoute: typeof ProviderProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LogisticsRoute: LogisticsRoute,
  OrdersRoute: OrdersRoute,
  ParcelsRoute: ParcelsRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  RegisterRoute: RegisterRoute,
  RoadmapRoute: RoadmapRoute,
  StayRoute: StayRoute,
  TiffinRoute: TiffinRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ProviderProviderIdRoute: ProviderProviderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
